### ISSUE TITLE
Application crash on SIP003 connnect.

### ISSUE THREAD

**Issue by arbabseyfola** [Qv2ray/QvPlugin-SS#2]
Qv2ray crashed when connection to SS with sip003 plugin. where to place [SIP003 ](https://github.com/shadowsocks/v2ray-plugin)plugin?
Can you provide an example?

**Comment by darsvador** [comment]
@arbabseyfola  烦请使用dev(2.7.0-pre1)版本qv2ray测试一下 https://github.com/Qv2ray/QvPlugin-SS/actions/runs/263782334 插件能否正常使用
(插件接口已更新到v3)

**Comment by darsvador** [comment]
目前Linux用户与Windows用户都有反馈最新版本插件([v1.3](https://github.com/Qv2ray/QvPlugin-SS/releases/tag/v1.3))已经可以正常使用,有问题欢迎反馈,本issue关闭了.
