### ISSUE TITLE
老旧的计算机上运行出现 “非法指令” / SIGILL 等情况

### ISSUE THREAD

**Issue by lapoize** [Qv2ray/QvPlugin-SS#6]
Qv2ray version:2.6.3
QvPlugin-SS version:1.3
v2ray-plugin version:1.3.1
系统:Ubuntu 20.04.2 LTS
内核:5.8.0-44-generic
**Qv2ray Debug日志：**
[INIT]: Qv2ray PreInitialization: OK
[INIT]: Qv2ray 2.6.3 on Ubuntu 20.04.2 LTS x86_64
[CORE-UI]: Successfully installed a translator for zh_CN
[LICENCE]: 
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.

Copyright (c) 2019-2020 Qv2ray Development Group.
Third-party libraries that have been used in Qv2ray can be found in the About page.

[INIT]: Application exec path: /tmp/.mount_Qv2rayXw9hdN/usr/bin
[INIT]: Path: /tmp/.mount_Qv2rayXw9hdN/usr/bin/config/ does not contain a valid config file.
[CORE-SETTINGS]: Found a config file, v= path=/home/user_name/.config/qv2ray/
[INIT]: Using /home/user_name/.config/qv2ray/ as the config path.
[CORE-UI]: Removed translations
[CORE-UI]: Successfully installed a translator for zh_CN
[COMMON-NETWORK]: Current OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
[CORE-UI]: Found factory style: Windows
[CORE-UI]: Found factory style: Fusion
[CORE-UI]: Found QSS style at: ":/uistyles/flatwhite.css"
[CORE-UI]: Found QSS style at: ":/uistyles/psblack.css"
[COMPONENT-PLUGINHOST]: Reloading plugin list
[COMPONENT-PLUGINHOST]: Loaded plugin: "SS Plugin" made by: "Qv2ray Development Group"
[PLUGIN-CLIENT-qvplugin_ss]: Initialize plugin.
[CORE-UI]: Applying UI style: Windows
[CORE-UI]: Loading data...
[COMMON-NETWORK]: Start checking update for channel ID: 0
[COMPONENT-UPDATE]: Received update info:
 --> Latest: 2.6.3
 --> Current: 2.6.3
 --> Ignored: 0.0.0
[COMPONENT-UPDATE]: No suitable updates found on channel 0
[CORE-CONNECTION]: Inserting default values to simple config
[QV2RAY-CORE]: Cannot disconnect when there's nothing connected.
[CORE-CONNECTION]: Creating kernel plugin instance for protocolshadowsocks-sip003
[CORE-VCORE]: V2RayIntegration: 15000 = shadowsocks-sip003
[CORE-CONNECTION]: Sending connection settings to kernel.
[CORE-CONNECTION]: Outbound protocol freedom is not a registered plugin outbound.
[CORE-CONNECTION]: Outbound protocol blackhole is not a registered plugin outbound.
[CORE-CONNECTION]: Applying new outbound settings.
[CORE-VCORE]: Starting kernels with V2RayIntegration.
[CORE-CONNECTION]: Starting kernel for protocol: shadowsocks-sip003
[CORE-VCORE]: Core ABI: ELF amd64 可执行文件
[CORE-VCORE]: Host ABI: ELF amd64 可执行文件
[CORE-VCORE]: Host is compatible with core
[CORE-VCORE]: V2Ray output: V2Ray 4.35.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16 linux/amd64);A unified platform for anti-censorship.
[CORE-UI]: ProxyAddress: 127.0.0.1
[COMPONENT-PROXY]: Setting up System Proxy
[COMPONENT-PROXY]: Qv2ray will set system proxy to use HTTP
[COMPONENT-PROXY]: Qv2ray will set system proxy to use SOCKS
[CORE-VCORE]: gRPC Version: 1.19.1
[CORE-VCORE]: API call returns: 14 (Connect Failed)
[CORE-VCORE]: API call returns: 14 (channel is in state TRANSIENT_FAILURE)
[CORE-VCORE]: API call returns: 14 (channel is in state TRANSIENT_FAILURE)
[CORE-VCORE]: API call returns: 14 (channel is in state TRANSIENT_FAILURE)
[CORE-UI]: Setting current item.
非法指令 (核心已转储)

**Comment by DuckSoft** [comment]
**非法指令**

这个错误一般是因为你的 CPU 型号过于老旧且不支持部分指令导致的。请报上您的计算机的主处理器（CPU）的型号。

**Comment by lapoize** [comment]
> **非法指令**
> 
> 请报上您的计算机的主处理器（CPU）的型号。

Intel Core i7-3612QE(thinkpad X230)

**Comment by DuckSoft** [comment]
看起来问题的根源在于这款 2012 年第二季度发行的 CPU 不支持 AVX2 指令集，而项目依赖中可能使用到的一个叫 libsodium 的库在构建环境中并不缺少 AVX2 指令集，因此构建出的二进制文件无法正常在您的电脑上运行。

若您有一定的技术水平，可以阅读本项目仓库下 `.github/workflow/` 的构建流程文件，尝试在您的电脑上自行编译一个没有 AVX2 指令集的版本；若您没有相关技术，请耐心等待我们的项目维护者 @darsvador 进行处理。

ps: 目前 QvPlugin-SS 和 QvPlugin-SSR 均有这个问题，但 QvPlugin-SSR 此前已经提供了 noavx 版本。

**Comment by darsvador** [comment]
@lapoize 我之后会加入🈚avx指令插件编译，敬请留意
