### ISSUE TITLE
rc4-md5协议未识别

### ISSUE THREAD

**Issue by wk989898** [Qv2ray/QvPlugin-SS#7]
Qv2ray 版本 v2.6.3:5840
插件版本 
QvPlugin-SS.v1.3.Windows-x64.dll

插件已开启，连接ss发生 unknown cipher method: rc4-md5 然后提示启动失败

**Comment by wk989898** [comment]
![O 1FMNP4 C0$AU_{0NW}QLB](https://user-images.githubusercontent.com/55834428/122157076-cd543500-ce9c-11eb-95f0-86f99d604e07.png)

**Comment by MarksonHon** [comment]
你插件开启了，那么你把协议换成shadowsocks-sip了么？

**Comment by wk989898** [comment]
怎么换？

Markson Hon ***@***.***> 于 2021年6月16日周三 14:31写道：

**Comment by MarksonHon** [comment]
@wk989898 

你加群吧：https://t.me/qv2ray_chat
![图片](https://user-images.githubusercontent.com/50002150/122213630-bc76e400-cedb-11eb-8b65-c1e8d18d349d.png)

**Comment by wk989898** [comment]
感谢！
